def add_five(num):
    return num + 5 #Forced error for pytest to catch, error now rectified for test to pass